### ISSUE TITLE
How to start dashboard on 0.0.0.0

### ISSUE THREAD

**Issue by raphaelsoul** [ethersphere/bee-dashboard#111]
global installed via npm. 
but listen on localhost:8080 only.
is there config file or environment variables available for changing running host?

**Comment by matmertz25** [comment]
See https://github.com/ethersphere/bee-dashboard/issues/110#issuecomment-846618836. In order to get bee to run on 0.0.0.0 you need to edit your configuration file https://docs.ethswarm.org/docs/working-with-bee/configuration#configuring-bee-installed-using-a-package-manager and make sure that **api-addr** and **debug-api-addr** are set to _:1634_ and _:1635_ with no local host and **debug-api-enable** is set to true.
