### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by caesarchad** [ethersphere/bee-dashboard#117]
hi guys, this tool is amazing, i have translated the content and do a Chinese language localizaton.
Could you please tell me where i can post my work and merge into the main branch?

**Comment by luoyuu77** [comment]
搭建好之后可以局域网内访问么

**Comment by vojtechsimetka** [comment]
Hi @caesarchad thank you very much for this offer and I will gladly take it later on. The Bee-dashboard is still in a very much alpha stage and we will be evolving the tool significantly soon. It also right now does not have the necessary internationalization plugins to make translations easy. Given these constraints we would like to for now keep it only in english so that we can better engage with the communities using it.

**Comment by jlfsccm** [comment]
请问windows怎么使用 谢谢
