### ISSUE TITLE
Show private key

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-dashboard#21]
It would be quite useful to be able to retrieve private key (probably only after hitting some reveal button) so that it can be easily copied into 3rd party wallet.

**Comment by agazso** [comment]
Generally that's not a good idea so it would be better to understand the use-case. If it's to be copied into a 3rd party wallet app, it's better to use the encrypted JSON V3 wallet format. Otherwise this would require having an API endpoint on Bee that exposes the raw private key, which may end up a security issue.
