### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Feebusiness** [ethersphere/bee-dashboard#94]
Access to XMLHttpRequest at 'http://xx.xx.xx.xx:1635/chequebook/address' from origin 'http://xx.xx.xx.xx:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 Access to XMLHttpRequest at 'http://xx.xx.xx.xx:1635/topology' from origin 'http://xx.xx.xx.xx:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 Access to XMLHttpRequest at 'http://xx.xx.xx.xx:1635/health' from origin 'http://xx.xx.xx.xx:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by matmertz25** [comment]
@Feebusiness you need to modify your bee nodes configuration file to be able to connect to the APIs from the browser / bee-dashboard. Basically your getting those errors because of something called Cross-Origin-Resource-Sharing [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) which is a security measure enforced by the browser. You need to explicitly tell your bee node what IPs/domains to allow access to. By default, access is restricted to protect bee node operators from exposing certain functionality on their bee nodes accidentally. 

1. Find and modify bee config file 
You can find your config file at `/etc/bee/bee.yaml` if your on linux. 
See here https://docs.ethswarm.org/docs/installation/configuration

2. Modify the "cors-allowed-origins" parameter
Modify the array to include either your IP address/addresses from which you are accessing it from OR add "*" which can be used to allow any IP address to access the APIs (be careful with this though if your firewall is not configured to block unintended traffic)
See here in the docs https://docs.ethswarm.org/docs/installation/configuration#--cors-allowed-origins.
See here for more info on finding your IP and other networking considerations https://docs.ethswarm.org/docs/installation/connectivity

3. Restart your bee node
Run `sudo systemctl restart bee`  if your on linux

**Comment by tfius** [comment]
or use this
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by Feebusiness** [comment]
Thanks a lot！

> @Feebusiness you need to modify your bee nodes configuration file to be able to connect to the APIs from the browser / bee-dashboard. Basically your getting those errors because of something called Cross-Origin-Resource-Sharing [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) which is a security measure enforced by the browser. You need to explicitly tell your bee node what IPs/domains to allow access to. By default, access is restricted to protect bee node operators from exposing certain functionality on their bee nodes accidentally.
> 
> 1. Find and modify bee config file
>    You can find your config file at `/etc/bee/bee.yaml` if your on linux.
>    See here https://docs.ethswarm.org/docs/installation/configuration
> 2. Modify the "cors-allowed-origins" parameter
>    Modify the array to include either your IP address/addresses from which you are accessing it from OR add "*" which can be used to allow any IP address to access the APIs (be careful with this though if your firewall is not configured to block unintended traffic)
>    See here in the docs https://docs.ethswarm.org/docs/installation/configuration#--cors-allowed-origins.
>    See here for more info on finding your IP and other networking considerations https://docs.ethswarm.org/docs/installation/connectivity
> 3. Restart your bee node
>    Run `sudo systemctl restart bee`  if your on linux

thanks! this issue has been solved！

**Comment by 1058745043** [comment]
Я использую настройки nginx для отображения прокси - сервера, которые, как ожидается, будут полезны для вас
